### PR TITLE
refactor: rename udev rule

### LINKED ISSUE #98: The `TAG+="uaccess"` has no effect in the udev rule
As hinted [here](https://github.com/systemd/systemd/issues/4288#issuecomment-348166161), udev `uaccess` is granted by  `/usr/lib/udev/rules.d/73-seat-late.rules`. So having a rule add the `uaccess` tag after `73-seat-late.rules` ran has not effect. The rules are ran in lexical order, so to be compatible with the `uacccess` system, the rule must be renamed, i.e. to `70-CH341.rules`.

https://github.com/bigbigmdm/IMSProg/blob/062b2f0488d2e8fc4adbabaffbff6fb958ad26f2/IMSProg_programmer/other/99-CH341.rules#L3-L3

### PR DESCRIPTION
**Pull request by wucke13**
This fixes #98. Essentially, the processing of udev rules in lexical order rendered the `TAG+="uaccess"` in the IMSProg udev rule useless. This commit fixes it by renaming the rules file, causing it to be processed before the internal handling of udev's `uacccess`.

### CODE REVIEW

**Comment by bigbigmdm** [comment]
"Collective Intelligence" concluded that the file name would be better to make `71-CH341.rules` and remove the obsolete definitions `MODE="0660", GROUP="plugdev"`.

**Comment by wucke13** [comment]
@bigbigmdm No problem, I can adjust accordingly. Is there a changelog somewhere? This will become a breaking change, when we remove `plugdev`. Hence it should be noted in the changelog/release notes.

**Comment by bigbigmdm** [comment]
I have changed these files. You can check the changelog in the [latest](https://github.com/bigbigmdm/IMSProg/releases/tag/v1.4.1) release. If you can check the German translation - I would be glad. (Please see [here](https://github.com/bigbigmdm/IMSProg?tab=readme-ov-file#Translations) and [here](https://github.com/bigbigmdm/IMSProg/issues/80)).

**Comment by Fantu** [comment]
New version was already released without update the changelog, anyway at least release notes is complete.
I try to suggest again to have more extended and complete changelog (https://github.com/bigbigmdm/IMSProg/issues/19#issuecomment-2076780658) instead keep one line for version and incomplete even if is in [dedicate file](https://github.com/bigbigmdm/IMSProg/blob/main/ChangeLog)

**Comment by Fantu** [comment]
@bigbigmdm Don't delete the release, don't have important issue and now the project is followed and used by many people and distro, so is better to avoid bad things.
Changelog improvements can be done now (also improving some old version entries) and for newer version but without override the latest release/tag.

**Comment by bigbigmdm** [comment]
@Fantu , please help to write a correct `debian/changelog` file.

**Comment by Fantu** [comment]
I suppose should start from something like:
```
imsprog (1.4.1-1) unstable; urgency=medium

  * New upstream version
    - Renamed udev rule from 99-CH341.rules to 71-CH341.rules (for uaccess)
      and removed MODE=660 and GROUP+=plugdev
  * Fix debian/watch
```

**Comment by bigbigmdm** [comment]
@Fantu, are previous records required:

```imsprog (1.3.9-1) unstable; urgency=medium

  * New upstream version (Closes: #1070883)
  * Update debian/copyright
  * d/control: add qttools5-dev to build-deps
  * d/rules: add all hardening
  * Bump debhelper compat to 13
  * Bump Standards-Version to 4.7.0, no needed changes

 -- Mikhail Medvedev <e-ink-reader@yandex.ru>  Mon, 13 May 2024 15:09:18 +0300

imsprog (1.3.2-1) unstable; urgency=medium

  * Initial release (Closes: #1057386)

 -- Mikhail Medvedev <e-ink-reader@yandex.ru>  Mon, 26 Feb 2024 13:16:51 +0300```

**Comment by Fantu** [comment]
yes all are uploaded version (https://tracker.debian.org/pkg/imsprog/news/) so must be keeped

**Comment by bigbigmdm** [comment]
Thank you, @Fantu ! I'm finally starting to understand something. :)

**Comment by wucke13** [comment]
@bigbigmdm so I can close this PR, since you've implemented the respective changes already?

**Comment by wucke13** [comment]
This was already fixed by 947320fca4878b46beefbee05e47279c3b27f94e, hence this PR is obsolete.

**Comment by bigbigmdm** [comment]
@wucke13 , Yes, thank you for your help!

**Comment by wucke13** [comment]
> I have changed these files. You can check the changelog in the [latest](https://github.com/bigbigmdm/IMSProg/releases/tag/v1.4.1) release. If you can check the German translation - I would be glad. (Please see [here](https://github.com/bigbigmdm/IMSProg?tab=readme-ov-file#Translations) and [here](https://github.com/bigbigmdm/IMSProg/issues/80)).

I did so, find my results here: https://github.com/bigbigmdm/IMSProg/pull/102

**Comment by bigbigmdm** [comment]
@wucke13 , thank you! Can you also check the desktop and metadata files:
[IMSProg_programmer/other/IMSProg.desktop](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_programmer/other/IMSProg.desktop)
[IMSProg_programmer/other/IMSProg_editor.desktop](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_editor/other/IMSProg_editor.desktop)
[IMSProg_programmer/other/IMSProg_database_update.desktop](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_programmer/other/IMSProg_database_update.desktop)

[IMSProg_programmer/other/imsprog.appdata.xml](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_programmer/other/imsprog.appdata.xml)
[/IMSProg/blob/main/IMSProg_programmer/other/imsprog.database.update.appdata.xml](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_programmer/other/imsprog.database.update.appdata.xml)
[IMSProg/blob/main/IMSProg_editor/other/imsprog.editor.appdata.xml](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_editor/other/imsprog.editor.appdata.xml)

[/IMSProg_programmer/other/IMSProg_database_update](https://github.com/bigbigmdm/IMSProg/blob/main/IMSProg_programmer/other/IMSProg_database_update)

**Pull request closed without merging**
