### PR TITLE
minor fix for Italian translation

### PR DESCRIPTION
**Pull request by giovanni69**
This is another minor fix for the Italian translation.
Please, merge it.
Thanks!

### CODE REVIEW

**Comment by bigbigmdm** [comment]
@giovanni69 , Ok!
Please translate me also the phrase `%description
IMSProg - I2C, MicroWire and SPI EEPROM/Flash chip Programmer - 
is a program to read, write EEPROM chips use the CH341A 
programmer device. The IMSProg makes respect to QHexEdit2 
hex editor and SNANDer programmer.

IMSProg is a collection of tools:
IMSProg - the chip programmer (it's the main part).
IMSProg_editor - chip database editor.
IMSProg_database_update - script to update chip database using 
external web-server.` - for the RedHat/Fedora spec file.

**Comment by giovanni69** [comment]
IMSProg - Programmatore di chip EEPROM/Flash I2C, MicroWire e SPI -
è un programma per leggere e scrivere chip EEPROM utilizzando il programmatore CH341A.
IMSProg usa l'editor esadecimale QHexEdit2 ed il programmatore SNANDer.

IMSProg è una raccolta di strumenti:
IMSProg - il programmatore di chip (è la parte principale).
IMSProg_editor - editor del database dei chip.
IMSProg_database_update - script per aggiornare il database dei chip, utilizzando un server web esterno.
` - per il file delle specifiche di RedHat/Fedora.

**Comment by bigbigmdm** [comment]
Thank you, @giovanni69 !

**Comment by giovanni69** [comment]
Please, could you also update the chipEditor_en_IT.qm file?
Thanks!
If you need other translations, you can write to me at scafora.giovanni@gmail.com

**Comment by bigbigmdm** [comment]
I've already built it.

**Comment by giovanni69** [comment]
> I've already built it.

I still see "Add file via upload 5 months ago"

**Comment by bigbigmdm** [comment]
I'm sorry! - chip**Editor**

**Comment by giovanni69** [comment]
Спасибо

**Comment by bigbigmdm** [comment]
@giovanni69 , Please  see also the files: 
`IMSProg_programmer/other/IMSProg_database_update.desktop`
`IMSProg_programmer/other/IMSProg.desktop`
`IMSProg_editor/other/IMSProg_editor.desktop`

**Comment by giovanni69** [comment]
Yes, I saw them. Do I have to translate those .desktop files to the Italian language?

**Comment by bigbigmdm** [comment]
Please correct (if necessary) the translation lines:
Comment[it]=
GenericName[it]=
Keywords[it]=

**Comment by giovanni69** [comment]
Done!

**Comment by giovanni69** [comment]
I want to inform you that IMSProg is also available for Arch Linux at https://aur.archlinux.org/packages/imsprog

**Comment by bigbigmdm** [comment]
Yeah, I know. This package was built by [Christopher James Kent](https://github.com/kjkent).

**Comment by giovanni69** [comment]
I have been using Arch Linux since 2005, and I have been an Arch Linux developer for 10 years.
I translated and still maintain the Italian translations of the pacman package manager and AUR.

**Pull request merged**
