### PR TITLE
Update chipProgrammer_pt_BR.ts

### PR DESCRIPTION
**Pull request by alexandrecleite**
Translation of new menu item. "Export to Intel HEX"

### CODE REVIEW

**Comment by bigbigmdm** [comment]
Thanks, @alexandrecleite . This is a small update. If you have a desire to help the project, please see (issue52)[https://github.com/bigbigmdm/IMSProg/issues/52]

**Comment by bigbigmdm** [comment]
Hello, @alexandrecleite  !
Can you help me with the translation into Brazilian of my new project - [SFP master](https://github.com/bigbigmdm/SFP-Master) ?

**Comment by alexandrecleite** [comment]
Hello Mikhail!
Yes, of course i can. Send me more details, please.

Alexandre

Em qua., 11 de dez. de 2024 às 07:20, Mikhail Medvedev <
***@***.***> escreveu:

**Comment by alexandrecleite** [comment]
Can you send me a english .ts file

Em qua., 11 de dez. de 2024 às 07:20, Mikhail Medvedev <
***@***.***> escreveu:

**Comment by bigbigmdm** [comment]
@alexandrecleite , please visit [SFP master](https://github.com/bigbigmdm/SFP-Master). The README.md file has a brief instruction about it in `Translations` section. Can you copy the file [SFP-Master_it_IT.ts](https://github.com/bigbigmdm/SFP-Master/blob/main/language/SFP-Master_it_IT.ts) to `SFP-Master_pt_BR.ts` and change in this file the Italian translations to Brazilian translations?

**Comment by alexandrecleite** [comment]
Hello Mikhail!
Here are the files translated to pt_BR.
I made it based on the Italian translation.
If I missed anything, please let me know.

Best regards, Alexandre

Em ter., 17 de dez. de 2024 às 16:50, Mikhail Medvedev <
***@***.***> escreveu:

**Comment by bigbigmdm** [comment]
I'm sorry, where is these files?

**Comment by alexandrecleite** [comment]
They were attached to the email. Didn't they get there?
Sending zipped now.

Em qua., 18 de dez. de 2024 às 13:28, Mikhail Medvedev <
***@***.***> escreveu:

**Comment by bigbigmdm** [comment]
@alexandrecleite Thank you! 
This is a great job!

P.S. This is a very unusual method of file transfer. Usually many people do `pull request`....

**Comment by bigbigmdm** [comment]
@alexandrecleite , thank you!
transl

**Comment by alexandrecleite** [comment]
You're welcome! 🙂
________________________________
De: Mikhail Medvedev ***@***.***>
Enviado: quinta-feira, 19 de dezembro de 2024 08:17
Para: bigbigmdm/IMSProg ***@***.***>
Cc: Alexandre C. Leite ***@***.***>; Mention ***@***.***>
Assunto: Re: [bigbigmdm/IMSProg] Update chipProgrammer_pt_BR.ts (PR #51)


@alexandrecleite<https://github.com/alexandrecleite> , thank you!
transl.png (view on web)<https://github.com/user-attachments/assets/a118b1fe-891e-466a-83bd-54a273854d74>

**Comment by bigbigmdm** [comment]
Hello @alexandrecleite , @giovanni69 , @blackPantherOS ! I have prepared a new version of IMSProg with new form - SPI NOR FLASH security registers. I need help with the translation... Can you help me ?

**Pull request merged**
