### PR TITLE
Debian improvements

### PR DESCRIPTION
**Pull request by Fantu**
@bigbigmdm Some other small fixes
d/copyright I hope is now ok, ftp-master will do deep check before accept new package in Debian repository

I think you can try to do a new upload to mentors after merge this, but without do a new release (with only packaging fixes and improvement can be done only when all finished and ok)

### CODE REVIEW

**Comment by Fantu** [comment]
@bigbigmdm there are these stills missed in d/control:
```
Vcs-Git: https://github.com/bigbigmdm/IMSProg.git
Vcs-Browser: https://github.com/bigbigmdm/IMSProg/
```

**Comment by bigbigmdm** [comment]
These lines should be inserted after the "Homepage" line in debian/control?

**Comment by bigbigmdm** [comment]
My dput was crashed:
```
dput mentors imsprog_1.1.4_source.changes
Checking signature on .changes
gpg: /home/mimi/Документы/C_and_CPP/DEBIAN-PACKAGE/1140/imsprog_1.1.4_source.changes: Valid signature from 18AB7E84797DA922
Checking signature on .dsc
gpg: /home/mimi/Документы/C_and_CPP/DEBIAN-PACKAGE/1140/imsprog_1.1.4.dsc: Valid signature from 18AB7E84797DA922
Traceback (most recent call last):
  File "/usr/bin/dput", line 11, in <module>
    load_entry_point('dput==1.0.3+ubuntu1.1', 'console_scripts', 'execute-dput')()
  File "/usr/share/dput/dput/dput.py", line 1030, in main
    files_to_upload = verify_files(
  File "/usr/share/dput/dput/dput.py", line 447, in verify_files
    raise dputhelper.DputUploadFatalException(
dput.helper.dputhelper.DputUploadFatalException: Error: uploading files for distribution UNRELEASED to mentors not allowed.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_dput_execute-dput.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/dput", line 11, in <module>
    load_entry_point('dput==1.0.3+ubuntu1.1', 'console_scripts', 'execute-dput')()
  File "/usr/share/dput/dput/dput.py", line 1030, in main
    files_to_upload = verify_files(
  File "/usr/share/dput/dput/dput.py", line 447, in verify_files
    raise dputhelper.DputUploadFatalException(
dput.helper.dputhelper.DputUploadFatalException: Error: uploading files for distribution UNRELEASED to mentors not allowed.

```

**Comment by Fantu** [comment]
If UNRELEASED is not possible anymore, do `dch -r --distribution unstable` for temp. finalize d/changelog to generate source build for mentors upload, but don't push the d/changelog finalize and release as other changes may be needed (I think is don't good do new release any minimal packages changes, especially if it's not even uploaded to official repo)

**Comment by Fantu** [comment]
To be more specific, you can commit the release commit keeping only in local git copy, when more changes are needed you will remove the temp. commit (for example you can remove the latest commit with `git reset --hard HEAD~1`, do the needed changes, push them to github, do another temp. release commit and do for another mentors upload.

**Comment by bigbigmdm** [comment]
I updated dput-ng and the dput command loads with status ok!

**Comment by bigbigmdm** [comment]
Benjamin Drung (bdrung)[https://github.com/bdrung] seemed to promise to take care of the package, but then stopped replying to emails. Can you contact him?

**Comment by Fantu** [comment]
You can try to ask on #debian-mentors on IRC for a sponsor and advices

**Comment by Fantu** [comment]
There is also a bind on matrix if you prefer matrix instead IRC

**Comment by bigbigmdm** [comment]
Fabio, thank you so much for everything you have done for me!

**Comment by bigbigmdm** [comment]
Fabio, good day! Did I understand correctly that I need to delete the debian folder here, make a new debian/latest branch and copy the debian folder into that branch?

**Comment by Fantu** [comment]
If is ok for you, start to remove debian folder from main branch and release/tag 1.1.4
I'll try to prepare debian/latest branch for you and do a test to check what is better to do for import upstream with gbp and try to make easier/fast as possible

**Comment by bigbigmdm** [comment]
Fabio, take a look, please. Is it right?

**Comment by Fantu** [comment]
Why the 1.1.4 tag point to https://github.com/bigbigmdm/IMSProg/commit/92a9567afff591ad26fe93849d8c90aa550a89d8 ?
Should point to https://github.com/bigbigmdm/IMSProg/commit/33200511de7ba8fbafab1718d237d25109077164
will be the upstream release
the debian release will be generated with gbp
about debian/latest I should try to start from empty branch and check working `gbp import-orig`

**Comment by bigbigmdm** [comment]
Fabio, I'm confused.
I write:
```
git tag v1.1.4 debian/latest
git push origin v1.1.4

```
Is it right?

**Comment by Fantu** [comment]
v1.1.4 tag should be the upstream tag on main branch
debian tags will be generated with `gbp tag`, and pushed after that upload will be accepted to official repository

**Comment by bigbigmdm** [comment]
Oops ;) Just moment, please. 
```
git tag v1.1.4 main
```
Is it right?

**Comment by Fantu** [comment]
Yes, if you can replace it after I'll try import of upstream with gbp

**Comment by bigbigmdm** [comment]
Ok, thank you!

**Comment by Fantu** [comment]
I still see the wrong 1.1.4 tag

**Comment by bigbigmdm** [comment]
What's it like now?

**Comment by Fantu** [comment]
tag is ok, gbp import did wrong, I need to ask on mentors, probably I did something wrong

**Comment by bigbigmdm** [comment]
Thank you very much! I look forward to hearing more from you!

**Comment by Fantu** [comment]
Found a solution, I wrote the correct command for future import in debian/README.source
if you want to replace debian/latest with my here seems ok: https://github.com/Fantu/IMSProg/tree/debian/latest

**Comment by Fantu** [comment]
Another thing after view another readd of debian/ in main e remove of it, main will now have only upstream things and not packaging one that will remain only in debian/latest, plus other possible debian/* and ubuntu/* branches when needed (based on https://dep-team.pages.debian.net/deps/dep14/), for example when package will be added on Debian and after migrate to Debian testing debian/bookworm-backports branch for doing a backports for Debian 12

**Comment by Fantu** [comment]
I take a look at your branches but seems chaotic, why another add and remove of debian/ in main? As wrote, main should not have packaging anymore.
About debian/latest was not replaced but added commit with changes, I don't know if gbp import can merge correctly the next merge of history from main set as now.
And about major of commit "Add files via upload", should be good short description of what the commit do and if needed extended with more details, this can be useful in many cases.
So a developer who sees a git repository like this would probably run away ^^'
About unofficial build (for example for launchpad ppa) push branches is not needed, you can do a local-only branch with only d/changelog entry for rebuild (in major of case only this needed).

If you give me permission I'll do a "clean" debian/latest, as for now nothing was released a replacement with force push should be ok, on main even if not good latest commits probably is not good force push and override history if other users/developers use it.

**Comment by bigbigmdm** [comment]
"I take a look at your branches but seems chaotic, why nother add and remove of debian/ in main?"
- I accidentally got the wrong branch.

"Если вы дадите мне разрешение, я сделаю "чистый" debian/latest"
- Do I have to do something on GitHub to give you permission?
-

**Comment by Fantu** [comment]
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/permission-levels-for-a-personal-account-repository#collaborator-access-for-a-repository-owned-by-a-personal-account

**Comment by bigbigmdm** [comment]
I invited you the IMSProg repository.

**Comment by Fantu** [comment]
I realized that yesterday I had made a stupid mistake with debian/gbp.conf which had made me waste time in numerous attempts with gbp import-ref, now it went right as it should and put the correct command in debian/README.source
now should be correct:
https://github.com/bigbigmdm/IMSProg/commits/debian/latest/
try to do an upload to mentors

**Comment by Fantu** [comment]
About upstream (the software) in the main branch, a changelog not linked to packaging but only the software itself I think is needed. If the commits and their descriptions were done well, they could also be generated quickly and easily with each new version https://www.freecodecamp.org/news/a-beginners-guide-to-git-what-is-a-changelog-and-how-to-generate-it/

**Comment by bigbigmdm** [comment]
Good day, Fabio! 
Am I reading this right?
1. On my computer I make a `git switch debian/latest`
2. `git pull`
3. I build the package version 1.1.4-1
4. Upload it to `debian.mentors`

**Comment by bigbigmdm** [comment]
Fabio, I don't get it. Why did we make it then?

Can you go into detail, step by step?

**Comment by bigbigmdm** [comment]
```
git log
commit 1235d82c3aa206be8c12618738759708ea1d8054 (HEAD -> debian/latest, origin/debian/latest)
Author: Fabio Fantoni <fantonifabio@tiscali.it>
Date:   Sat Jan 6 20:02:57 2024 +0100

    debian: add README.source with the command to use for import new upstream version

commit 4cceb700e3eaf853961a1d75710a817e2d799c16
Author: Fabio Fantoni <fantonifabio@tiscali.it>
Date:   Sun Jan 7 21:17:49 2024 +0100

    update changelog

commit ccf764bb090110e9bfdf788fb8abb754b1c0cf5d
Merge: 61104b2 1761b82
Author: Fabio Fantoni <fantonifabio@tiscali.it>
Date:   Sun Jan 7 21:12:32 2024 +0100

    Update upstream source from tag 'v1.1.4'
    
    Update to upstream version '1.1.4'
    with Debian dir b960bbb7f272990584861211694b38f5d197dbfb

commit 61104b2869efbeb1d8f841800775747fb9d3c958
Author: Fabio Fantoni <fantonifabio@tiscali.it>
Date:   Sun Jan 7 21:07:34 2024 +0100

    add debian/gbp.conf

commit 27bfb6df59827562430c58b2e9ca791ef17fb193
Author: Fabio Fantoni <fantonifabio@tiscali.it>
Date:   Sat Jan 6 16:10:12 2024 +0100

    put a previous version for test import of new upstream version

commit 78074eb8daea8924b1d53684457dcbd97816a603
Author: Fabio Fantoni <fantonifabio@tiscali.it>
Date:   Sat Jan 6 15:44:27 2024 +0100

    debian: add upstream metadata

commit d41294348e39ca0be1ffd4cee68c77fe89737252
Author: Fabio Fantoni <fantonifabio@tiscali.it>
Date:   Sat Jan 6 15:43:06 2024 +0100

    d/control: specify debian/latest branch in vcs

commit 3da5cd1bcadddfc6ec3d47d34b2c7e3ee2562d21
Author: Fabio Fantoni <fantonifabio@tiscali.it>
Date:   Sat Jan 6 15:22:02 2024 +0100

    debian: switch format to quilt

commit 945b4d24e0927ab1b9cbc9fb3af5e0f60ce898ee
Author: Fabio Fantoni <fantonifabio@tiscali.it>
Date:   Sat Jan 6 15:20:46 2024 +0100

    clean debian/changelog

commit 30f0dd0034b5e71864ca34afaedb3298c84bbeae
Author: Fabio Fantoni <fantonifabio@tiscali.it>
Date:   Sat Jan 6 15:19:12 2024 +0100

    debian: initial packaging from older upstream one

commit 1761b82e22dbe94c4985d94d130db922c07b5fd4 (tag: v1.1.4, main)
Author: Mikhail Medvedev <75389103+bigbigmdm@users.noreply.github.com>
Date:   Sat Jan 6 16:55:47 2024 +0300
    Delete debian directory

commit 38a13f3dcbc5cb8667268951aee5d449ccf565bc
Merge: 3320051 92a9567
Author: Mikhail Medvedev <75389103+bigbigmdm@users.noreply.github.com>
Date:   Sat Jan 6 16:55:01 2024 +0300
```
Is it Ok?
Can I compiling and uploading this folder to mentors.debian?

**Comment by Fantu** [comment]
yes

**Comment by bigbigmdm** [comment]
Thanks, Fabio!
The download was successful. (https://mentors.debian.net/package/imsprog/)

Can you please tell me what to do next?

**Comment by Fantu** [comment]
now seems ok, ramain only the lintian error for IMSProg_programmer/other/index.html, is it a generated file or is a "false positive"? (in the second case an add of lintian ovveride is needed)

**Comment by bigbigmdm** [comment]
I tested the file IMSProg_programmer/other/index.html at https://validator.w3.org/ and got zero errors. But lintian still fails on it. Maybe the file is too big. In index.html images in BASE64 format are inserted into the file itself.

**Comment by Fantu** [comment]
lintian report about that file seems a generated one and without source present. w3 validation do another type of check.
so the question is if the file is automatically generated with source don't present on repository or is a simple html file that you modify munually (with whatever editor you use). In that case will be added a lintian override

**Comment by bigbigmdm** [comment]
This is not a generated file, I made it myself.

**Comment by Fantu** [comment]
I pushed to debian/latest 2 other commits, including the lintian override for this error
do a git pull, add a temp. release commit (dch -r --distribution unstable), don't push it, and do new upload to mentors. delete also all olders upload (from mentors page).
If it will be accepted you will push the temp. release commit, if other changes are needed you will delete it.

**Comment by bigbigmdm** [comment]
Good evening Fabio!
I have uploaded the latest changes to mentors.debian.
Please take a look at them.

**Comment by Fantu** [comment]
Unfortunately the d/changelog is wrong :( , I don't know how you managed to make 2 new entries with a simple `dch -r --distribution unstable` on UNRELEASED while for the rest it seems that the right username and email fields are not set on git (see root@mimi-HP -Laptop-15s-eq1xxx).
For set them globally (if you don't have some project with different mail) should be for example:
```
git config --global user.name "Mikhail Medvedev"
git config --global user.email "e-ink-reader@yandex.ru"
```
For delete the wrong commit/s you can do for example:
`git reset --hard fb224c27f9972c450ad888983329ceac0145d04d`
fb224c27f9972c450ad888983329ceac0145d04d is the hash of my latest commit

After redoing `dch -r --distribution unstable` should keep 1.1.4-1 only entry with your right name and email for correct upload to mentors (the wrong should be deleted)

**Comment by bigbigmdm** [comment]
Okay. I'll do it tomorrow. I just don't have the energy today. If I get something wrong, will you help me?

**Comment by bigbigmdm** [comment]
Thanks Fabio! I uploaded the latest changes to mentors.debian. Everything is now green!

Now what do I do next? Write to the chat again asking for package sponsorship?

**Comment by Fantu** [comment]
From a fast look now seems ok, try to ask again in mentors chat for a sponsor, maybe now with several things fixed/improved there will be more chance of finding a DD that want to check and sponsor

**Comment by Fantu** [comment]
Probably is useful to close the old RFS (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057076) that is wrong and open a new one taking the template autogenerated from latest mentors upload, if you are not sure to do right try to send a mail to me instead submit@bugs.debian.org before

**Comment by bigbigmdm** [comment]
Fabio, please see this messages:

Message1:
--------
1057386-done@bugs.debian.org
Subject: bug#1057386
The request has been moved to RFS. 

Message2:
---------
submit@bugs.debian.org
Subject: RFS: imsprog/1.1.4-1 [put in ITP, ITA, RC, NMU if applicable] -- friendly greeter

Package: sponsorship-requests
Severity: normal [important for RC bugs, wishlist for new packages]

Dear mentors,

I am looking for a sponsor for my package "imsprog":

    Package name         : imsprog
    Version              : 1.1.4-1
    Upstream contact     : Mikhail Medvedev e-ink-reader@yandex.ru
    URL                  : https://github.com/bigbigmdm/IMSProg/archive/refs/tags/v1.1.4.tar.gz
    License              : GPL-2+, GPL-3+, LGPL-2.1
    Homepage             : https://github.com/bigbigmdm/IMSProg
    Vcs-Git              : https://github.com/bigbigmdm/IMSProg.git -b debian/latest
    Vcs-Browser          : https://github.com/bigbigmdm/IMSProg/
    Section              : devel

The source builds the following binary packages:

        IMSProg - i2c,SPI,MW chips programmer for CH341a devices
        IMSProg_editor - chip database editor for the IMSProg
        IMSProg_database_update - online chip database update from the external web-server.

To access further information about this package, please visit the following URL:

        https://github.com/bigbigmdm/IMSProg
        https://launchpad.net/imsprog

Alternatively, you can download the package with 'dget' and wget using this commands:

        dget https://mentors.debian.net/debian/pool/main/i/imsprog/imsprog_1.1.4-1.dsc
        wget https://github.com/bigbigmdm/IMSProg/archive/refs/tags/v1.1.4.tar.gz

Changes since the last upload:

 imsprog (1.1.4-1) unstable; urgency=medium
 .
   * Initial release (Closes: #1057386)


Regards,
-- 
  M. Medvedev

**Comment by Fantu** [comment]
The ITP must remain open, will be automatically closed only when upload to official repository will be accepted by ftp-master.

message1: Is the wrong RFS to close (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057076)

message2:
About the new one to open is correct, only some small things to change:

Subject: `RFS: imsprog/1.1.4-1 [ITP] -- friendly greeter`

on severity line remove the part `[important for RC bugs, wishlist for new packages]` and change `normal` to `wishlist` (as explained in the text)
and below "To access further information about this package, please visit the following URL:" must be and not upstream repository and unofficial build on launchpad what is being done is for builds in the official debian repositories (and thanks to the auto sync from debian also in ubuntu and derivatives)

    https://mentors.debian.net/package/imsprog/

in theory, it should already be right in the template

**Comment by bigbigmdm** [comment]
Fabio, I'm duplicating here before posting just in case:

Message2:
---------
submit@bugs.debian.org
Subject: RFS: imsprog/1.1.4-1 [ITP] -- friendly greeter

Package: sponsorship-requests
Severity: wishlist

Dear mentors,

I am looking for a sponsor for my package "imsprog":

    Package name         : imsprog
    Version              : 1.1.4-1
    Upstream contact     : Mikhail Medvedev e-ink-reader@yandex.ru
    URL                  : https://github.com/bigbigmdm/IMSProg/archive/refs/tags/v1.1.4.tar.gz
    License              : GPL-2+, GPL-3+, LGPL-2.1
    Homepage             : https://github.com/bigbigmdm/IMSProg
    Vcs-Git              : https://github.com/bigbigmdm/IMSProg.git -b debian/latest
    Vcs-Browser          : https://github.com/bigbigmdm/IMSProg/
    Section              : devel

The source builds the following binary packages:

        IMSProg - i2c,SPI,MW chips programmer for CH341a devices
        IMSProg_editor - chip database editor for the IMSProg
        IMSProg_database_update - online chip database update from the external web-server.

To access further information about this package, please visit the following URL:

        https://mentors.debian.net/package/imsprog/

Alternatively, you can download the package with 'dget' and wget using this commands:

        dget https://mentors.debian.net/debian/pool/main/i/imsprog/imsprog_1.1.4-1.dsc
        wget https://github.com/bigbigmdm/IMSProg/archive/refs/tags/v1.1.4.tar.gz

Changes since the last upload:

 imsprog (1.1.4-1) unstable; urgency=medium
 .
   * Initial release (Closes: #1057386)


Regards,
-- 
  M. Medvedev 


Is everything correct now?

**Comment by Fantu** [comment]
I hadn't noticed before, but I suppose you replaced the part too `The source builds the following binary packages:`
the generated binary package is only one, so this seems you change the right autogenerated content of template with this wrong.

I don't have to upload to mentors at the moment as these days I'm working on packages for which I have upload permissions, but if I remember correctly the template autogenerated by mentors is correct and with only 1-2 small system things.

**Comment by bigbigmdm** [comment]
Okay. I mixed up binary packages - it's a DEB package, it's one. But there are three executable files in it. I'll fix it in mail and send it to Debian.

**Comment by Fantu** [comment]
binary packages != binary executable (there can also be multiple executables in a package)

I also still saw old wrong RFS (1057076) open, better close before open the new one

**Comment by Fantu** [comment]
One DD replies on mentors page, /lib/udev/rules.d should be moved for next debian and ubuntu.
I was thinking about the best way to do it, I don't know if better in upstream (on cmake build) or in packaging to build.
For detecting the path to use I suppose can be used `pkg-config --variable=udevdir udev`

**Comment by bigbigmdm** [comment]
Fabio, you wrote: "I also still saw old wrong RFS (1057076) open, better close before open the new one".
In order to close bug#105076 I need to send an email like this:

```
[1057386-done@bugs.debian.org](mailto:1057386-done@bugs.debian.org)
Subject: bug#1057386
The request has been moved to RFS.
```
Am I understanding this correctly?

**Comment by Fantu** [comment]
For close bug#1057076 must be 1057076-done@bugs.debian.org https://www.debian.org/Bugs/Developer#closing

**Comment by bigbigmdm** [comment]
I have the file arrangement into folders in IMSProg_programmer/CMakeLists.txt:
String 111:
```
install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/other/99-CH341.rules" DESTINATION "/lib/udev/rules.d")
```

**Comment by bigbigmdm** [comment]
Fabio, when i closing bug#1057076, what do need specify in the message body? (What's the reason for the closure?)

**Comment by Fantu** [comment]
I suppose the cause can be "old and wrong", about open the new instead wait, need to fix udev rules and do new upload

**Comment by bigbigmdm** [comment]
CMake can use prefixes such as:
```
# Set the CMAKE_INSTALL_PREFIX to /usr if not specified
if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
	set(CMAKE_INSTALL_PREFIX "/usr" CACHE PATH "The default install prefix" FORCE)
endif()
```
But for the rule files, I haven't found the  examples.

**Comment by bigbigmdm** [comment]
Actually the path /lib/udev/rules.d prompted me lintian. True, I have the penultimate version of Ubuntu.

**Comment by Fantu** [comment]
Should don't change the default path, need to set new cmake variable for udev destination like UDEV_CMAKE_INSTALL_DIR and set in it `pkg-config --variable=udevdir udev`+/rules.d and use this variable like
`install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/other/99-CH341.rules" DESTINATION ${UDEV_CMAKE_INSTALL_DIR})`
but I don't have time to try to do it

**Comment by bigbigmdm** [comment]
Good afternoon, Fabio!
The more I learn about CMake, the more questions I have. Here are my variables that CMake gets from the Linux environment:

```
-- CMAKE_INSTALL_BINDIR=bin
-- CMAKE_INSTALL_DATADIR=share
-- CMAKE_INSTALL_DATADIR=share
-- CMAKE_INSTALL_DATAROOTDIR=share
-- CMAKE_INSTALL_DEFAULT_COMPONENT_NAME=Unspecified
-- CMAKE_INSTALL_DOCDIR=share/doc/IMSProg
-- CMAKE_INSTALL_DOCDIR=share/doc/IMSProg
-- CMAKE_INSTALL_FULL_BINDIR=/usr/local/bin
-- CMAKE_INSTALL_FULL_DATADIR=/usr/local/share
-- CMAKE_INSTALL_FULL_DATAROOTDIR=/usr/local/share
-- CMAKE_INSTALL_FULL_DOCDIR=/usr/local/share/doc/IMSProg
-- CMAKE_INSTALL_FULL_INCLUDEDIR=/usr/local/include
-- CMAKE_INSTALL_FULL_INFODIR=/usr/local/share/info
-- CMAKE_INSTALL_FULL_LIBDIR=/usr/local/lib
-- CMAKE_INSTALL_FULL_LIBEXECDIR=/usr/local/libexec
-- CMAKE_INSTALL_FULL_LOCALEDIR=/usr/local/share/locale
-- CMAKE_INSTALL_FULL_LOCALSTATEDIR=/usr/local/var
-- CMAKE_INSTALL_FULL_MANDIR=/usr/local/share/man
-- CMAKE_INSTALL_FULL_OLDINCLUDEDIR=/usr/include
-- CMAKE_INSTALL_FULL_RUNSTATEDIR=/usr/local/var/run
-- CMAKE_INSTALL_FULL_SBINDIR=/usr/local/sbin
-- CMAKE_INSTALL_FULL_SHAREDSTATEDIR=/usr/local/com
-- CMAKE_INSTALL_FULL_SYSCONFDIR=/usr/local/etc
-- CMAKE_INSTALL_INCLUDEDIR=include
-- CMAKE_INSTALL_INFODIR=share/info
-- CMAKE_INSTALL_INFODIR=share/info
-- CMAKE_INSTALL_LIBDIR=lib
-- CMAKE_INSTALL_LIBEXECDIR=libexec
-- CMAKE_INSTALL_LOCALEDIR=share/locale
-- CMAKE_INSTALL_LOCALEDIR=share/locale
-- CMAKE_INSTALL_LOCALSTATEDIR=var
-- CMAKE_INSTALL_MANDIR=share/man
-- CMAKE_INSTALL_MANDIR=share/man
-- CMAKE_INSTALL_OLDINCLUDEDIR=/usr/include
-- CMAKE_INSTALL_PREFIX=/usr
-- CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT=1
-- CMAKE_INSTALL_RUNSTATEDIR=var/run
-- CMAKE_INSTALL_RUNSTATEDIR=var/run
-- CMAKE_INSTALL_SBINDIR=sbin
-- CMAKE_INSTALL_SHAREDSTATEDIR=com
-- CMAKE_INSTALL_SO_NO_EXE=1
-- CMAKE_INSTALL_SYSCONFDIR=etc
```

If you look at `CMAKE_INSTALL_FULL_...`, it appears that the system is asking for executables to be located in `/usr/local/bin` instead of `/usr/bin`. Is this correct?

**Comment by bigbigmdm** [comment]
Fabio, can you compile /debian/latest in the latest version of Ubuntu and let me know the path to the rules file?

**Comment by Fantu** [comment]
These should be the default values (for users that do custom build without specify them), Debian packaging set them to the needed.
In debian/latest (and other packaging branches) MUST don't have changes out of Debian folder, any packaging specific changes to upstream source must use quilt (or gbp pq) and patches will be in debian/patches. Probably in this case with one binary package and without specific things dh_auto_install should take all files as installed by the build system and no packaging changes are need when fixed upstream.
This change should be done upstream as also other distro are doing usr merge.
From a fast look the change seems to me wrong because udev change may differ from the global lib one, so any software I saw are managing udev dir instead for doing the correct thing (I don't found one using cmake to see the correct setting to do)

**Comment by bigbigmdm** [comment]
I used (GNUInstallDirs)[https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html] to read the correct linux patches.

**Comment by Fantu** [comment]
I mean that udev path changes may be moved differently from general lib one so should be considered itself.
All softwares I saw use 2 method, automatically set it like mdadm (I suppose the best) or make it settable by parameter (which would possibly be set via debian/rules)

**Comment by bigbigmdm** [comment]
Fabio, I'm sorry! What is mdadm?

**Comment by Fantu** [comment]
mdadm is for manage software raid, but don't use cmake, in its makefile I saw a good and minimal way to make udevdir:
```
UDEVDIR := $(shell $(PKG_CONFIG) --variable=udevdir udev 2>/dev/null)
ifndef UDEVDIR
 UDEVDIR = /lib/udev
endif
```

about cmake with udev rules I found only this:
https://github.com/mixxxdj/mixxx/blob/main/CMakeLists.txt
probably you can make a minimal and optimal thing looking it
In it the full procedure is long, I don't know if it is done due to cmake shortcomings

**Comment by bigbigmdm** [comment]
Fabio, thanks for the cmake example. I will definitely have a look at it.

**Comment by Fantu** [comment]
About commit message in latest main commit I saw for example:
```
Add files via upload
Fixed invalid path
```
I think should be only "Fixed invalid path" and "Add files via upload" is useless.

For make commit in easier/fast way you can use a gui tool, for example I use git-cola, while for most other things I continue to use the git commands from the cli (git fetch/pull/push/rebase/reset etc...)

**Comment by bigbigmdm** [comment]
Hello Fabio!
I put the tag 1.1.6, but `gbp import-ref -u1.1.6` returned the error: `Import of upstream/1.1.6 failed: Error while executing git tag: fatal: Failed to resolve "upstream/1.1.6^0" as a link.`.

**Comment by Fantu** [comment]
The 1.1.6 tag seems ok, I suppose you have issue on your local git, I suggest cloning the repository in a new folder to have a clean and correct local copy

**Comment by Fantu** [comment]
@bigbigmdm In https://mentors.debian.net/package/imsprog/ you missed enabling "sponsor need" flag

**Comment by bigbigmdm** [comment]
Thank you, Fabio, for helping me! I'm very grateful to you!

**Pull request merged**
